#!/usr/bin/env bash

AVAILABLE_ENV="BEHAT_PARAMS IDE_PHPUNIT_CUSTOM_LOADER IDE_PHPUNIT_PHPUNIT_PHAR IDE_PHPUNIT_VERSION IDE_PHPUNIT_PHPUNIT_INCLUDE IDE_BEHAT_DIR IDE_BEHAT_PHAR IDE_BEHAT_VERSION ${DHP_EXPORT_ENV}"
ARG_ENV=""

for VAR_NAME in ${AVAILABLE_ENV}; do
    if [[ -n ${!VAR_NAME} ]]; then
        ARG_ENV="-e $VAR_NAME=${!VAR_NAME} $ARG_ENV"
    fi
done